"""Added FSRS speed grading column

Revision ID: 885d4f01a4ad
Revises: 
Create Date: 2026-04-01 01:36:28.752329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885d4f01a4ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprinkler_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vacation_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vacation_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_review_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('daily_review_limit')
        batch_op.drop_column('vacation_start_date')
        batch_op.drop_column('vacation_mode')
        batch_op.drop_column('sprinkler_tokens')

    # ### end Alembic commands ###
